project_id = "czmnkrurkzuerrcjzbkp"

[functions.import-from-api]
verify_jwt = false

[functions.boleto-whatsapp-flow]
verify_jwt = false

[functions.search-patient-by-cpf]
verify_jwt = false

[functions.check-sindical-associado-by-cpf]
verify_jwt = false

[functions.mobile-booking-init]
verify_jwt = false

[functions.send-homologacao-email]
verify_jwt = false

[functions.send-homologacao-reminders]
verify_jwt = false

[functions.send-homologacao-protocol]
verify_jwt = false
