project_id = "eahhszmbyxapxzilfdlo"

[functions.send-whatsapp]
verify_jwt = true

[functions.send-whatsapp-document]
verify_jwt = true

[functions.send-appointment-reminders]
verify_jwt = false

[functions.evolution-api]
verify_jwt = true

[functions.clinic-api]
verify_jwt = false

[functions.dispatch-webhook]
verify_jwt = true

[functions.notify-new-signup]
verify_jwt = false

[functions.create-public-booking]
verify_jwt = false

[functions.telemedicine]
verify_jwt = true
